// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4mP4lbVlY0PfCSPJdfwTNIASZgKihIjg',
    appId: '1:1091608067897:web:3fb9398e4ee65ee17732e8',
    messagingSenderId: '1091608067897',
    projectId: 'wemet-72365',
    authDomain: 'wemet-72365.firebaseapp.com',
    storageBucket: 'wemet-72365.appspot.com',
    measurementId: 'G-PBB044Q4BC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCh9djUNkKFEaSu85itm4O3OfdFgmvYCyI',
    appId: '1:1091608067897:android:3a3479827def724d7732e8',
    messagingSenderId: '1091608067897',
    projectId: 'wemet-72365',
    storageBucket: 'wemet-72365.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRQTU09_bfdF8gPaVRbUmiOPuPu4Xs4Q4',
    appId: '1:1091608067897:ios:33edbfcc6a4632c87732e8',
    messagingSenderId: '1091608067897',
    projectId: 'wemet-72365',
    storageBucket: 'wemet-72365.appspot.com',
    iosBundleId: 'com.example.wemet',
  );
}
